if [ "$API" -ge 26 ]; then
  if [ -n "$QCP" ]; then FBUF="$Q_FBUF"; elif [ -n "$TENZ" ]; then FBUF="$T_FBUF"; else FBUF=1; fi
  case "$FBUF" in frames) append "aaudio.hw_burst_min_usec=8000" "aaudio.mixer_bursts=2" ;; latency) append "aaudio.hw_burst_min_usec=1000" ;; *) append "aaudio.hw_burst_min_usec=4000" "aaudio.mixer_bursts=2" ;; esac; [ -n "$U_AAEM" ] && append "aaudio.mmap_policy=3" "aaudio.mmap_exclusive_policy=3"
fi
[ "$API" -ge 28 ] && append "ro.vendor.audio.usb.period_us=20375"; [ "$API" -ge 30 ] && { [ "$U_APFF" == "force" ] && append "media.extractor.float=true" "media.decoder.hw_extrct=true" "media.stagefright.audio.cbk=true" "persist.vendor.audio.float_dec.flbk=true"; }; [ -n "$U_APDBR" ] && append "audio.deep_buffer.media=false" "media.stagefright.audio.deep=false"; append "af.resampler.quality=7" "ro.audio.resampler.psd.enable_at_samplerate=44100" "ro.audio.resampler.psd.cutoff_percent=100" "ro.audio.resampler.psd.tbwcheat=0" "ro.audio.ignore_effects=false" "ro.aac_drc_effect_type=-1" "aac_drc_heavy=0" "aac_drc_cut=0" "aac_drc_boost=0" "aac_drc_enc_target_level=0" "aac_drc_reference_level=-1" "ro.audio.usb.period_us=20375" "persist.vendor.bt.a2dp.hw_cdc=true" "persist.bluetooth.bqr.vnd_trace_mask=0"; [ -n "$U_HL" ] && append "ro.audio.resampler.psd.halflength=$U_HL"; [ -n "$U_SBA" ] && { [ "$U_SBA" -gt 144 ] && append "ro.audio.resampler.psd.stopband=144" || append "ro.audio.resampler.psd.stopband=$U_SBA"; }; [ -n "$U_VSTP" ] && { [ "$U_VSTP" -gt 100 ] && append "ro.config.media_vol_steps=100" || append "ro.config.media_vol_steps=$U_VSTP"; }
if [ -n "$U_BTDAO" ]; then
  append "ro.bluetooth.a2dp_offload.supported=false" "ro.bluetooth.leaudio_offload.supported=false" "persist.bluetooth.a2dp_offload.enable=false" "persist.bluetooth.a2dp_offload.disabled=true" "persist.bluetooth.bluetooth_audio_hal.disabled=true" "persist.bluetooth.leaudio_offload.disabled=true"; sed -i -E 's/persist.vendor.bt.a2dp.hw_cdc=false/persist.vendor.bt.a2dp.hw_cdc=true/' "$PERPROP"; [ -n "$QCP" ] && append "vendor.audio.feature.a2dp_offload.enable=false"
fi
if [ -n "$U_BTDAV" ]; then
  append "vendor.btstack.absolute_volume=false" "persist.vendor.btstack.absolute_volume=false" "persist.vendor.btsatck.absvolfeature=false" "persist.bluetooth.disableabsvol=true" "persist.vendor.bt.a2dp.absvolfeature=false"
fi
if [ -n "$QCP" ]; then
  append "audio_hal.period_size=192" "audio_hal.period_multiplier=1" "audio.hwacceffects.needed=false" "effect.reverb.pcm=0" "audio.safx.pbe.enabled=false" "audio.pp.asphere.enabled=false" "audio.nat.codec.enabled=true" "audio.sys.routing.latency=0" "ro.vendor.audio.feature.fade=false" "vendor.audio.lowpower=false" "vendor.audio.tunnel.encode=false" "vendor.audio.use.dts_eagle=false" "vendor.audio.adm.buffering.ms=1" "vendor.audio.hph_mbdrc.enabled=false" "vendor.audio.matrix.limiter.enable=false" "vendor.audio.kpi_optimize.enable=true" "vendor.audio.battery_listener.enable=false" "vendor.audio.hal.buf_oflow.ptrace.mon=false" "vendor.audio.hal.dynamic.qos.config.supported=true" "vendor.audio.hal.output.suspend.supported=true" "vendor.audio.volume.headset.gain.depcal=false" "vendor.audio.feature.ext_hw_plugin.enable=false" "vendor.audio.feature.hwdep_cal.enable=false" "vendor.audio.feature.hifi_audio.enable=true" "vendor.audio.feature.kpi_optimize.enable=true" "vendor.audio.feature.battery_listener.enable=false" "vendor.audio.feature.matrix.limiter.enable=false" "vendor.audio.feature.dmabuf.cma.memory.enable=false" "vendor.audio.playback.mch.downsample=false" "vendor.audio.playback.dsp.pathdelay=false" "vendor.audio.usb.disable.sidetone=true" "persist.vendor.audio.hifi.int_codec=true" "persist.audio.hifi.int_codec=true"; [ -n "$U_APDBR" ] && append "vendor.audio.keep_alive.disabled=true" "vendor.audio.feature.keep_alive.enable=false" "vendor.audio.feature.deepbuffer_as_primary.enable=false"; [ -z "$D_PROPS" ] && append "persist.vendor.audio.c2.conc.hw_sw=true" "persist.vendor.audio.sva.conc.enabled=false" "persist.vendor.audio.va_concurrency_enabled=false" "persist.vendor.audio.hw_hal.fallback.enabled=true" "persist.vendor.audio.pwr_buck_mode.enabled=true" "persist.vendor.audio.power.save.setting=false" "persist.vendor.bt.a2dp.strct-xmem-ctl=-1" "persist.vendor.bt.a2dp.aac_whitelist=true" "persist.vendor.qcom.bluetooth.aac_vbr_ctl.enabled=true" "persist.vendor.bt.aac_vbr_frm_ctl.enabled=true"; { [ -n "$Q_CBIT_PROCEED" ] && { [ "$Q_CBIT" = "S24_3LE" ] || [ "$Q_CBIT" = "S24_LE" ]; }; } || { [ -n "$Q_HDSPBW" ] && [ "$Q_HDSPBW" = "24" ]; } && { append "persist.audio.format.24bit=true"; [ "$API" -ge 29 ] && append "persist.vendor.audio.format.24bit=true"; }
  if strings "$BTDEF" 2>/dev/null | grep -q 'com\.qualcomm\.qti\.bluetooth_audio@.*\.so' || strings "$BTDEF64" 2>/dev/null | grep -q 'com\.qualcomm\.qti\.bluetooth_audio@.*\.so' || strings "$BTDEF" 2>/dev/null | grep -q 'parse src cap ret =' || strings "$BTDEF64" 2>/dev/null | grep -q 'parse src cap ret ='; then
    append "persist.bluetooth.sbc_hd_higher_bitrate=1" "persist.bt.sbc_hd_higher_kbps=1"
  fi
  [ -z "$U_BT_KEEPFX" ] && strings "$PHAL64" 2>/dev/null | grep -q 'vendor\.audio\.spatial\.enable' && append "vendor.audio.spatial.enable=false"; [ -z "$U_BT_KEEPFX" ] && strings "$PHAL64" 2>/dev/null | grep -q 'ro\.vendor\.audio\.feature\.spatial' && append "ro.vendor.audio.feature.spatial=false"; [ "$API" -ge 29 ] && { append "vendor.audio_hal.period_size=192" "vendor.audio_hal.period_multiplier=1"; [ "$Q_CSMPL" == "KHZ_384" ] && sed -i -E 's/ro.mediacodec.max_sample_rate=192000/ro.mediacodec.max_sample_rate=384000/' "$SYSPROP"; }
  if [ "$Q_FBUF" == "latency" ]; then
    sed -i -E 's/audio_hal.period_size=192/audio_hal.period_size=48/' "$SYSPROP"; sed -i -E 's/vendor.audio_hal.period_size=192/vendor.audio_hal.period_size=48/' "$SYSPROP"; append "vendor.audio.adm.debug.noadm=true"; strings "$AUS64" 2>/dev/null | grep -q 'ro\.hardware\.audio\.tinyalsa\.period_count' && append "ro.hardware.audio.tinyalsa.period_count=1"; strings "$AUS64" 2>/dev/null | grep -q 'ro\.hardware\.audio\.tinyalsa\.period_size_multiplier' && append "ro.hardware.audio.tinyalsa.period_size_multiplier=1"; sed -i -E 's/ro.audio.usb.period_us=20375/ro.audio.usb.period_us=8000/' "$SYSPROP"; sed -i -E 's/ro.vendor.audio.usb.period_us=20375/ro.vendor.audio.usb.period_us=8000/' "$SYSPROP"
  elif [ "$Q_FBUF" == "frames" ]; then
    sed -i -E 's/audio_hal.period_size=192/audio_hal.period_size=1920/' "$SYSPROP"; sed -i -E 's/audio_hal.period_multiplier=1/audio_hal.period_multiplier=32/' "$SYSPROP"; sed -i -E 's/vendor.audio_hal.period_size=192/vendor.audio_hal.period_size=1920/' "$SYSPROP"; sed -i -E 's/vendor.audio_hal.period_multiplier=1/vendor.audio_hal.period_multiplier=32/' "$SYSPROP"; sed -i -E 's/vendor.audio.adm.buffering.ms=1/vendor.audio.adm.buffering.ms=4/' "$SYSPROP"; strings "$AUS64" 2>/dev/null | grep -q 'ro\.hardware\.audio\.tinyalsa\.period_count' && append "ro.hardware.audio.tinyalsa.period_count=1"; strings "$AUS64" 2>/dev/null | grep -q 'ro\.hardware\.audio\.tinyalsa\.period_size_multiplier' && append "ro.hardware.audio.tinyalsa.period_size_multiplier=4"; sed -i -E 's/ro.audio.usb.period_us=20375/ro.audio.usb.period_us=30720/' "$SYSPROP"; sed -i -E 's/ro.vendor.audio.usb.period_us=20375/ro.vendor.audio.usb.period_us=30720/' "$SYSPROP"
  fi
  if find $(pfind "lib*") -maxdepth 1 -type f -name "libdsmfeedback.so" -print -quit 2>/dev/null | grep -q .; then
    append "vendor.audio.feature.dsm_feedback.enable=true"
  else
    append "vendor.audio.feature.dsm_feedback.enable=false"
  fi
  if find $(pfind "lib*") -maxdepth 1 -type f -name "libsndmonitor.so" -print -quit 2>/dev/null | grep -q . && [ "$Q_DSPOD" == "enable" ]; then
    append "vendor.audio.feature.snd_mon.enable=true"
  else
    append "vendor.audio.feature.snd_mon.enable=false"
  fi
  [ "$Q_CSMPL" == "KHZ_384" ] && sed -i -E 's/aaudio.hw_burst_min_usec(.?)8000/''d''/g' "$SYSPROP"; [ -n "$Q_MBDRC" ] && { append "vendor.audio.mspp.enable=false" "vendor.audio.vol_based_mbdrc.enabled=false"; [ -n "$RMA" ] && append "persist.vendor.audio.kv_mbdrc=false"; }
  if [ "$Q_DSPOD" == "disable" ]; then
    append "vendor.audio.qaf.enabled=false" "vendor.audio.qap.enabled=false" "vendor.audio.qaf.reencode=false" "vendor.audio.qap.reencode=false" "vendor.audio.qaf.passthrough=false" "vendor.audio.qap.passthrough=false" "vendor.audio.qap.output.block.handling=false" "audio.offload.disable=true" "audio.offload.pcm.enable=false" "audio.offload.track.enable=false" "audio.offload.pcm.16bit.enable=false" "audio.offload.pcm.24bit.enable=false"; [ "$API" -ge 26 ] && append "vendor.audio.offload.pcm.16bit.enable=false" "vendor.audio.offload.pcm.24bit.enable=false" "vendor.audio.offload.multiple.enabled=false" "vendor.audio.offload.track.enable=false" "vendor.audio.offload.gapless.enabled=false" "vendor.audio.offload.passthrough=false" "vendor.audio.offload.multiaac.enable=false" "vendor.audio.feature.afe_proxy.enable=false" "vendor.audio.feature.external_dsp.enable=false" "vendor.audio.feature.hdmi_passthrough.enable=false" "vendor.audio.feature.usb_offload.enable=false" "vendor.audio.feature.usb_offload_burst_mode.enable=false" "vendor.audio.feature.usb_offload_sidetone_volume.enable=false" "persist.vendor.audio.c2.dma.conc.enabled=true"
  elif [ "$Q_DSPOD" == "enable" ]; then
    append "vendor.audio.qaf.enabled=true" "vendor.audio.qap.enabled=true" "vendor.audio.qaf.reencode=true" "vendor.audio.qap.reencode=true" "vendor.audio.qaf.passthrough=true" "vendor.audio.qap.passthrough=true" "vendor.audio.qap.output.block.handling=true" "audio.offload.disable=false" "audio.offload.pcm.enable=true" "audio.offload.track.enable=true" "audio.offload.pcm.16bit.enable=true" "audio.offload.pcm.24bit.enable=true"; [ "$API" -ge 26 ] && append "vendor.audio.offload.pcm.16bit.enable=true" "vendor.audio.offload.pcm.24bit.enable=true" "vendor.audio.offload.multiple.enabled=true" "vendor.audio.offload.track.enable=true" "vendor.audio.offload.gapless.enabled=true" "vendor.audio.offload.passthrough=true" "vendor.audio.offload.multiaac.enable=true" "vendor.audio.feature.afe_proxy.enable=true" "vendor.audio.feature.hdmi_passthrough.enable=true" "vendor.audio.feature.external_dsp.enable=true" "vendor.audio.feature.usb_offload.enable=true" "vendor.audio.feature.usb_offload_burst_mode.enable=true" "vendor.audio.feature.usb_offload_sidetone_volume.enable=false" "persist.vendor.audio.c2.dma.conc.enabled=false"
  fi
  [ -n "$Q_HDSPBW" ] && append "persist.vendor.audio_hal.dsp_bit_width_enforce_mode=$Q_HDSPBW"
elif [ -n "$MTK" ]; then
  append "ro.hnd.analog.audio.max=155" "ro.hed.analog.audio.max=170" "ro.idle.nor.mic=250,250,250,250,250,250,250,250,250,250,250,250,250,250,250" "ro.idle.hed.mic=250,250,250,250,250,250,250,250,250,250,250,250,250,250,250" "ro.idle.hnd.mic=250,250,250,250,250,250,250,250,250,250,250,250,250,250,250" "ro.def.volume.music=14" "ro.def.volume.ring=14" "ro.def.volume.voice.call=6" "ro.def.volume.system=14" "ro.def.volume.alarm=12" "ro.def.volume.notification=10" "ro.def.volume.fm=14" "ro.def.volume.matv=6" "ro.def.volume.dtmf=6" "ro.def.volume.system.enforced=6" "ro.def.volume.bluetooth.sco=6" "ro.def.volume.volume.tts=10" "ro.nor.sph.vol=76,85,100,115,130,140,155" "ro.hed.sph.vol=72,84,96,108,120,132,145" "ro.hnd.sph.vol=72,84,96,108,120,132,145" "ro.hed.media.vol=0,21,39,57,75,93,111,129,147,165,183,201,219,237,255" "ro.hnd.media.vol=0,21,39,57,75,93,111,129,147,165,183,201,219,237,255" "ro.hnd.ring.vol=0,21,39,57,75,93,111,129,147,165,183,201,219,237,255" "ro.hed.ring.vol=0,21,39,57,75,93,111,129,147,165,183,201,219,237,255" "ro.dialpad.tone.volume=80" "ro.config.audio.speaker_boost=yes" "ro.have_aacencode_feature=1" "ro.mtk_audio_ape_support=1" "ro.mtk_flv_playback_support=1" "ro.mtk_wmv_playback_support=1"; [ -z "$D_PROPS" ] && append "vendor.audio.powerhal.power.hi_res=true" "vendor.audio.powerhal.power.hi_bitrate=true" "persist.af.losslessbt.on=1"
elif [ -n "$EXY" ]; then
  [ -z "$D_PROPS" ] && append "persist.audio.globaleffect=0" "persist.audio.soundalivefxsec=0" "persist.audio.uhqa=1"
fi
if [ -z "$D_PROPS" ]; then
  if [ -z "$U_OEM_KEEPFX" ]; then
    [ "$OEM" == "Oneplus" ] && append "ro.oplus.audio.effect.type=0" "ro.oplus.audio.dolby_multi_config=false" "ro.oplus.audio.effects.offload=false"; append "ro.vendor.audio.dolby.spatial.profile=undefine" "ro.vendor.audio.dolby.surround.enable=false"; [ -n "$MTK" ] && append "ro.vendor.audio.dolby.dax3_3point8=false" "ro.vendor.audio.dolby.dax.support=false"; [ "$OEM" == "Sony" ] && append "persist.sony.effect.dolby_atmos=false"
  fi
  [ -z "$U_BT_KEEPFX" ] && append "ro.audio.spatializer_enabled=false" "ro.audio.stereo_spatialization_enabled=false" "persist.vendor.audio.spatializer.speaker_enabled=false"
  if [ "$OEM" == "Xiaomi" ]; then
    [ -z "$U_OEM_KEEPFX" ] && append "ro.vendor.audio.sfx.spk.movie=true" "ro.vendor.audio.sfx.earadj=false" "ro.vendor.audio.sfx.scenario=false" "ro.vendor.audio.spk.stereo=true" "ro.vendor.audio.surround.support=true" "ro.vendor.audio.misound.bluetooth.enable=false" "ro.vendor.audio.soundfx.type=none" "ro.vendor.audio.soundfx.usb=false" "persist.vendor.audio.misound.disable=true" "persist.vendor.audio.misoundasc=false" "persist.vendor.audio.effectimplenter=none" "persist.vendor.audio.3dsurround.enable=false" "persist.vendor.audio.sfx.hd.music.state=0" "persist.vendor.audio.misound.scenario=0"; [ -z "$U_BT_KEEPFX" ] && append "persist.vendor.audio.spatializer.process=0"
  fi
  if [ "$OEM" == "Oneplus" ]; then
    append "vendor.audio.speaker.pm=0" "ro.oplus.audio.support.paboost=true" "persist.sys.bluetooth.qos_enable=1" "persist.oplus.a2dp_small_volume=false" "persist.oplus.audio.spllimit.on=false" "persist.bluetooth.a2dp_aac_abr.enable=false"; [ -z "$U_OEM_KEEPFX" ] && append "ro.oplus.audio.support.meta_audio=0"; [ -z "$U_BT_KEEPFX" ] && append "ro.audio.spatializer_type=none"; [ -n "$U_APDBR" ] && append "ro.oplus.audio.NoDefaultDeepbuffer=1"
  fi
  if [ -n "$MTK" ]; then
    [ "$M_COFF" == "enable" ] && append "vendor.streamout.offload.allow=1" "vendor.audiohal.resource.extdac.support=1" "persist.vendor.audio.usb.offload=true"; append "persist.vendor.audiohal.besloudness_state=0" "persist.vendor.audiohal.besloudness_state=0"
  fi
  if [ -n "$TENZ" ]; then
    if [ "$T_FBUF" == "latency" ]; then
      strings "$AUS64" 2>/dev/null | grep -q 'ro\.hardware\.audio\.tinyalsa\.period_count' && append "ro.hardware.audio.tinyalsa.period_count=1"; strings "$AUS64" 2>/dev/null | grep -q 'ro\.hardware\.audio\.tinyalsa\.period_size_multiplier' && append "ro.hardware.audio.tinyalsa.period_size_multiplier=1"; sed -i -E 's/ro.audio.usb.period_us=20375/ro.audio.usb.period_us=8000/' "$SYSPROP"; sed -i -E 's/ro.vendor.audio.usb.period_us=20375/ro.vendor.audio.usb.period_us=8000/' "$SYSPROP"
    elif [ "$T_FBUF" == "frames" ]; then
      strings "$AUS64" 2>/dev/null | grep -q 'ro\.hardware\.audio\.tinyalsa\.period_count' && append "ro.hardware.audio.tinyalsa.period_count=1"; strings "$AUS64" 2>/dev/null | grep -q 'ro\.hardware\.audio\.tinyalsa\.period_size_multiplier' && append "ro.hardware.audio.tinyalsa.period_size_multiplier=4"; sed -i -E 's/ro.audio.usb.period_us=20375/ro.audio.usb.period_us=30720/' "$SYSPROP"; sed -i -E 's/ro.vendor.audio.usb.period_us=20375/ro.vendor.audio.usb.period_us=30720/' "$SYSPROP"
    fi
    append "vendor.pixel.a2dp.dynamic.low.latency=on" "vendor.pixel.sco.super.wide.band=true"
  fi
  [ "$OEM" == "Sony" ] && [ -z "$U_OEM_KEEPFX" ] && append "audio.sony.effect.use.proxy=false" "vendor.audio.sony.effect.use.proxy=false" "ro.somc.dseehx.supported=false" "vendor.360ra.hrtf.wired=-1" "vendor.360ra.hrtf.bluetooth=-1" "vendor.360ra.upmix.headphone=-1" "vendor.360ra.upmix.cur_headphone=-1" "persist.sony.effect.ahc=false" "persist.sony.effect.clear_audio_plus=false"; [ "$OEM" == "LG" ] && append "ro.config.hifi_enhance_support=1" "persist.audio.hifi_adv_support=1" "persist.audio.hifi_dac=ON persist.audio.dmb_hifidac=true" "persist.lge.hifiquaddac=true"
  if find $(pfind "lib*") -maxdepth 1 -type f -name \( -name "libeffectozowidening.so" -o -name "libozowidening.so" \) -print -quit 2>/dev/null | grep -q . && [ -z "$U_OEM_KEEPFX" ]; then
    append "persist.audio.ozo_playback.enable=0"
  fi
fi
